# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y_d870AM27hfzKNJpyJAZ7s1iiPX7SEj
"""

ndvi = df[["date","ndvi"]].dropna()
ndvi["ndvi_roll30"] = ndvi["ndvi"].rolling(30, min_periods=1).mean()
ndvi["month"] = ndvi["date"].dt.month
seasonal_ndvi = ndvi.groupby("month")["ndvi"].mean()

fig, ax = plt.subplots(1,2, figsize=(14,5))
ax[0].plot(ndvi["date"], ndvi["ndvi_roll30"], color="forestgreen", lw=1.5)
ax[0].set(title="NDVI 30-Day Rolling Mean", xlabel="Date", ylabel="NDVI")

ax[1].bar(seasonal_ndvi.index, seasonal_ndvi.values, color="mediumseagreen")
ax[1].set_xticks(range(1,13))
ax[1].set(title="Average Seasonal NDVI Cycle", xlabel="Month", ylabel="NDVI")
plt.show()

ndti = df[["date","ndti"]].dropna()
ndti["ndti_roll30"] = ndti["ndti"].rolling(30, min_periods=1).mean()

plt.figure(figsize=(12,5))
plt.plot(ndti["date"], ndti["ndti_roll30"], color="chocolate", lw=1.5)
plt.title("NDTI (Turbidity Index) – 30-Day Rolling Mean")
plt.xlabel("Date")
plt.ylabel("NDTI")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# === Load the VIIRS dataset ===
file_path = '/content/Litani_VIIRS_Proxy_MODIS_NIR_Daily_Data.csv'
df_viirs = pd.read_csv(file_path)

# === Convert date column to datetime ===
df_viirs["date"] = pd.to_datetime(df_viirs["date"])

# === Extract relevant columns and drop NaN values ===
viirs = df_viirs[["date", "sur_refl_b02_mean"]].dropna()

# === Calculate 30-day rolling mean ===
viirs["viirs_roll30"] = viirs["sur_refl_b02_mean"].rolling(30, min_periods=1).mean()

# === Plot ===
plt.figure(figsize=(12, 5))
plt.plot(viirs["date"], viirs["viirs_roll30"], color="green", lw=1.5)
plt.title("VIIRS Reflectance (B02 Proxy) – 30-Day Rolling Mean")
plt.xlabel("Date")
plt.ylabel("Reflectance")
plt.grid(True, linestyle="--", alpha=0.6)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# --- Fix for NameError: name 'df' is not defined ---
# The DataFrame 'df' needs to be loaded and 'rain_roll30' calculated.
# Assuming 'Litani_WEFE_Stressed_Data.csv' is the source data.
file_path = '/content/Litani_WEFE_Stressed_Data.csv'
df = pd.read_csv(file_path)

# Convert the 'date' column to datetime objects
df['date'] = pd.to_datetime(df['date'])

# Calculate the 30-day rolling mean for rainfall.
# This assumes there is a column named 'rainfall' in the dataframe.
df['rain_roll30'] = df['rainfall'].rolling(30, min_periods=1).mean()
# --- End of Fix ---

# --- Rainfall-Only Visualization ---
plt.style.use("seaborn-v0_8-whitegrid")

fig, ax = plt.subplots(figsize=(14, 6))

ax.fill_between(
    df["date"], df["rain_roll30"],
    color="skyblue", alpha=0.35, label="Rainfall (mm)"
)

ax.plot(
    df["date"], df["rain_roll30"],
    color="skyblue", linewidth=1.5, alpha=0.6
)


ax.set_xlabel("Date", fontsize=12, fontweight="bold")
ax.set_ylabel("Rainfall (mm)", color="blue", fontsize=12, fontweight="bold")
ax.tick_params(axis='y', labelcolor='blue')
ax.grid(True, linestyle="--", alpha=0.4)

fig.suptitle(
    "Rainfall (30-Day Rolling Mean)",
    fontsize=16, fontweight="bold", y=1.03
)

ax.legend(loc="upper left")
plt.tight_layout()
plt.show()

